language: python

python:
  - "3.6"

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.18.1/bazel_0.18.1-linux-x86_64.deb
  - sha256sum -c bazel_0.18.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.18.1-linux-x86_64.deb
  - cd experiments

install:
  - pip install -r requirements.txt

script:
  - bazel test --test_output=streamed ...
